# Generated by Django 5.1.1 on 2024-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
