# Generated by Django 5.1.1 on 2024-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_products_cost_price_products_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
