# Generated by Django 5.1.1 on 2024-10-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_searchdate_alter_products_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
